#pragma once

#include "stormancer/headers.h"

#include "stormancer/Streams/bytestream.h"

#include "stormancer/PacketPriority.h"
#include "stormancer/Action.h"

#include "stormancer/ConnectionData.h"
#include "stormancer/ConnectToSceneMsg.h"
#include "stormancer/ConnectionResult.h"
#include "stormancer/DisconnectFromSceneDto.h"
#include "stormancer/RouteDto.h"
#include "stormancer/SceneInfosDto.h"
#include "stormancer/SceneInfosRequestDto.h"

#include "stormancer/DependencyResolver.h"
#include "stormancer/Helpers.h"

#include "stormancer/Client.h"
#include "stormancer/Configuration.h"
#include "stormancer/ConnectionState.h"
#include "stormancer/Logger/ILogger.h"
#include "stormancer/Logger/NullLogger.h"
#include "stormancer/Logger/ConsoleLogger.h"
#include "stormancer/Logger/FileLogger.h"
#include "stormancer/DefaultPacketDispatcher.h"
#include "stormancer/IConnection.h"
#include "stormancer/IConnectionManager.h"
#include "stormancer/IPacketProcessor.h"
#include "stormancer/IScenePeer.h"
#include "stormancer/ITransport.h"
#include "stormancer/MessageIDTypes.h"
#include "stormancer/SystemRequestIDTypes.h"
#include "stormancer/Packet.h"
#include "stormancer/PacketProcessorConfig.h"
#include "stormancer/PeerFilter.h"
#include "stormancer/RequestContext.h"
#include "stormancer/RequestModuleBuilder.h"
#include "stormancer/RequestProcessor.h"
#include "stormancer/Route.h"
#include "stormancer/Scene.h"
#include "stormancer/SceneDispatcher.h"
#include "stormancer/SceneEndpoint.h"
#include "stormancer/ScenePeer.h"
#include "stormancer/IPacketDispatcher.h"
#include "stormancer/IRequestModule.h"
#include "stormancer/ITokenHandler.h"
#include "stormancer/TokenHandler.h"
#include "stormancer/IScheduler.h"
#include "stormancer/DefaultScheduler.h"
#include "stormancer/Watch.h"
#include "stormancer/SyncClock.h"

#include "stormancer/IPlugin.h"

#include "stormancer/RPC/RpcPlugin.h"
#include "stormancer/RPC/RpcService.h"
#include "stormancer/RPC/RpcRequest.h"
#include "stormancer/RPC/RpcRequestContext.h"
